"""add payment_status and mercado_pago_order_id to orders

Revision ID: 560cd2a1ca52
Revises: 20260906_audit
Create Date: 2026-09-17 00:59:36.268746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560cd2a1ca52'
down_revision: Union[str, Sequence[str], None] = '20260906_audit'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = sa.Enum('PENDING', 'PAID', 'FAILED', name='payment_status')
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('orders', sa.Column('payment_status', payment_status_enum, server_default=sa.text("'PENDING'::payment_status"), nullable=False))
    op.add_column('orders', sa.Column('mercado_pago_order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'mercado_pago_order_id')
    op.drop_column('orders', 'payment_status')
    sa.Enum(name='payment_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
