"""add awaiting payment status and paid_at to orders

Revision ID: 5d93f147461d
Revises: 612630456ecf
Create Date: 2026-09-17 01:24:59.596575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d93f147461d'
down_revision: Union[str, Sequence[str], None] = '612630456ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'AWAITING_PAYMENT' BEFORE 'RECEIVED'")
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid_at')
    # Removing an enum value requires recreating the type; not supported in downgrade.
    # ### end Alembic commands ###
