"""add pix qr code fields to orders

Revision ID: 612630456ecf
Revises: 560cd2a1ca52
Create Date: 2026-09-17 01:14:03.949388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612630456ecf'
down_revision: Union[str, Sequence[str], None] = '560cd2a1ca52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('mercado_pago_payment_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('pix_qr_code', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('pix_qr_code_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pix_qr_code_base64')
    op.drop_column('orders', 'pix_qr_code')
    op.drop_column('orders', 'mercado_pago_payment_id')
    # ### end Alembic commands ###
